apiVersion: apps/v1
kind: Deployment
metadata:
  name: motobook-app-depl
  labels:
    run: motobook-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: motobook-app
  template:
    metadata:
      labels:
        run: motobook-app
    spec:
      containers:
        - image: lemorse/motobook-app:1.6
          name: motobook-app
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
